### ISSUE TITLE
 cannot be loaded as its extension is not registered in assetExts

### ISSUE THREAD

**Issue by salahbm** [tradingview/charting-library-examples#374]
Hi~
I am trying to implement chart on the expo SDK 50, have followed all the steps shown in the example. However, still facing same error on the `android`.

I tried to addd **`'js'`** in `metro.config.js` but didnt help...

`Error: 'android/app/src/main/assets/charting_library/charting_library.standalone.js' cannot be loaded as its extension is not registered in assetExts
    at getAsset (/Users/muhammad/Documents/react-native/coinkoops-app-frontend/node_modules/metro/src/Assets.js:198:11)
    at Server._processSingleAssetRequest (/Users/muhammad/Documents/react-native/coinkoops-app-frontend/node_modules/metro/src/Server.js:310:26)
`

<img width="448" alt="Screenshot 2024-03-28 at 4 13 14 PM" src="https://github.com/tradingview/charting-library-examples/assets/74946617/3109a2e6-acba-455c-be41-9db734f5da4c">

**Comment by graciott** [comment]
Same issue here

**Comment by Bishal-think201** [comment]
same issue here @salahbm @graciott any success?

**Comment by graciott** [comment]
I dont remember what i did. Worked on android but not on iOS. 
So, i released a web app and use a webview

@Bishal-think201

**Comment by Bishal-think201** [comment]
Had gone through few articles and open issues and understood the following in regards to expo, react-native for serving html, css and js file  ( If anyone reading this should help to get things speed up ).

1. We can use webview to server html file from an assets folder.
2. We cannot not server js file directly from the assets folder (There are too many open issues on this which i did not see any closure) .
3. A HTML file which has script tag is able to run the js code.

Below is something specific to Trading View usage in Mobile.
1. To run the trading view charts ( advance or any other ) we will first need to server it from a server and later use that in the webview to display trading view charts.

In case I have missed something, someone do add to this solution.

Hope this helps others.
