### ISSUE TITLE
Implement trading view in Java Application

### ISSUE THREAD

**Issue by antonylim** [tradingview/charting-library-examples#389]
Hi, I use JSP for the front end and Java Spring for the backend.
for the front end I copy the index.html part and change the datafeedUrl to my API.
in backend, I create some API:
1. http://localhost:8084/infovesta/saham/data/symbols
2. http://localhost:8084/infovesta/saham/data/history
3. http://localhost:8084/infovesta/saham/data/config
4. http://localhost:8084/infovesta/saham/data/time
5. http://localhost:8084/infovesta/saham/data/search
6. http://localhost:8084/infovesta/saham/data/symbols

all API use hardcode values, just for testing purposes.
It's not called http://localhost:8084/infovesta/saham/data/history API, so the graph did not show, what should I do?

![image](https://github.com/user-attachments/assets/dcbfb370-40fb-4169-9cc4-2d2399e714a0)

**Comment by GeorgiiMatveev-tv** [comment]
Hello @antonylim , 

Could you please set the property in the [widget constructor](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Widget-Constructor/) as `debug: true`, repeat loading of the page and send the log to us?

**Comment by antonylim** [comment]
Hi @GeorgiiMatveev-tv 
I don't see any message from the bottom right corner log button:
![image](https://github.com/user-attachments/assets/7ee179b4-7a1c-48db-b293-871d56c7f2ff)

**Comment by antonylim** [comment]
library.ed30e65….js:159 
 2024-08-16T01:53:36.469Z:Common.Delegate:Error: Incorrect entry syntax: 0930-163
    at _._parseSessionEntry (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:399:2203)
    at _.parseSessions (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:398:3008)
    at new v (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:400:226)
    at l.setSymbolInfo (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:380:2564)
    at c._updateSymbolInfo (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:708:1543)
    at c._onSymbolResolved (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:706:1716)
    at n._fireImpl (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:158:1461)
    at st.fireSymbolResolved (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:690:2272)
    at ut._onSymbolResolved (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:693:3046)
    at ut._onMessageImpl (http://localhost:8084/infovesta/resources/charting_library/bundles/library.ed30e65….js:692:2687)

**Comment by GeorgiiMatveev-tv** [comment]
Hello @antonylim 

One "0" seems to be missing from "0930-163", should be "0930-1630", most likely in the session or corrections information.

**Comment by antonylim** [comment]
Hi @GeorgiiMatveev-tv ,
can you give me pointer what should I do to fix it? and which API?

**Comment by antonylim** [comment]
Hi @GeorgiiMatveev-tv ,
i have succeed using TV Chart, but there are some error, can you give me pointer to resolved them?
![image](https://github.com/user-attachments/assets/8d3b3224-122d-4b3a-9615-e9b17b1f7215)

**Comment by GeorgiiMatveev-tv** [comment]
@antonylim , I suggest to address the CORS first, you'd need to implement your own storage for production, ours is only avaialbe for testing purposes on localhost. 
https://www.tradingview.com/charting-library-docs/latest/getting_started/Online-Editors/#note
